name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 34.57.24.211 >> ~/.ssh/known_hosts
          
      - name: Deploy to Server
        run: |
          ssh sosasjose.01@34.57.24.211 'cd /home/sosasjose.01/docker-gcp-deployment && git pull origin main && docker compose up -d --build'          
